<?php
session_start();
require '../config/db.php';

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    
    // Check if this is a registration submission
    if (isset($_POST['form_type']) && $_POST['form_type'] === 'register') {
        
        $username = trim($_POST['username']);
        $password = $_POST['password'];
        $full_name = trim($_POST['full_name']);
        $blood_group = $_POST['blood_group'];
        
        // Construct the strict BD Phone Number
        $raw_phone = trim($_POST['contact_phone']);
        // The form enforces 1XXXXXXXX format, so we just attach +880
        $contact_phone = '+880' . $raw_phone; 
        
        $latitude = $_POST['latitude'];
        $longitude = $_POST['longitude'];

        // Double-check the BD phone format in PHP just to be extra safe
        if (!preg_match('/^1[3-9][0-9]{8}$/', $raw_phone)) {
            die("Invalid BD Mobile Number format. Please go back and enter a valid number like 17XXXXXXXX.");
        }

        try {
            $pdo->beginTransaction();

            // 1. Verify username doesn't already exist
            $check_user = $pdo->prepare("SELECT user_id FROM users WHERE username = ?");
            $check_user->execute([$username]);
            if ($check_user->rowCount() > 0) {
                $pdo->rollBack();
                die("Username already exists! Please go back and choose a different username.");
            }

            // 2. Insert into 'users' table
            $password_hash = password_hash($password, PASSWORD_DEFAULT);
            $stmt1 = $pdo->prepare("INSERT INTO users (username, password_hash, role) VALUES (?, ?, 'Patient')");
            $stmt1->execute([$username, $password_hash]);
            
            // Grab the new ID generated by the database
            $new_user_id = $pdo->lastInsertId();

            // 3. Insert into 'patients' table (with is_donor flag activated)
            $stmt2 = $pdo->prepare("INSERT INTO patients (patient_id, full_name, blood_group, contact_phone, is_donor, latitude, longitude) VALUES (?, ?, ?, ?, 1, ?, ?)");
            $stmt2->execute([$new_user_id, $full_name, $blood_group, $contact_phone, $latitude, $longitude]);

            $pdo->commit();

            // 4. Auto-Login the new hero and redirect to their dashboard
            $_SESSION['user_id'] = $new_user_id;
            $_SESSION['role'] = 'Donor'; // Assigning Donor role for session access
            
            header("Location: ../donor_dashboard.php");
            exit();

        } catch (PDOException $e) {
            $pdo->rollBack();
            die("Database Error: " . $e->getMessage());
        }
    }
} else {
    // If someone tries to access this file directly without submitting the form
    header("Location: ../donor_register.php");
    exit();
}
?>